### ISSUE TITLE
Configuration error should not lead to installation error

### ISSUE THREAD

**Issue by pietdevaere** [netsec-ethz/bootstrapper#14]
Currently the installation of the bootstrapper fails if a configuration error occurs (specifically, if an unsigned configuration is received).

This is confusing to users.

It would be better to separate  configuration and installation errors.

**Proposed new behavior / installation flow**
- Upon installation, network configuration is attempted
- If configuration fails, installation still succeeds
- Result of configuration attempt is written to log. Either as "Configuration SUCCESS" or "Configuration FAILED: <more specific error>"
- Users are told (through print on CLI or out-of-band instructions) to check journalctl after installation to see if the network configuration was successful

**Comment by FR4NK-W** [comment]
Thank you for reporting this issue.

I like your suggestion.

The current behavior records the package status as `half-configured` if SCION bootstrapping was not successful.
The behavior proposed in this issue is to report the package as `installed` and ignore whether SCION bootstrapping was successful for the purpose of package installation and report the network configuration failure separately.

The behavior you propose has the advantage that the successful installation of the SCION bootstrapper is not conflated with the successful bootstrapping into a SCION network.
This is desirable when installing the package from a network that does not have SCION support, with the aim to have it later reconfigure the network configuration when in a network that does support SCION.
It is also fine when the package installation happens interactively as package installation and configuration success can be reported separately.
On the other hand, it has the drawbacks that it requires explicit notification of the user that the package was not able to perform its function and that in non-interactive mode neither the package state nor the unit state indicate if the network configuration was successful.

The proposed behavior is implemented in PR #15 :
>$git blame HEAD res/packaging/debian/DEBIAN/postinst | grep -v "#" | wc -l && git diff --stat
> 37
> res/packaging/debian/DEBIAN/postinst | 19 ++++++++++++++-----
> 1 file changed, 14 insertions(+), 5 deletions(-)

Note that explicitly logging the last configuration attempt result of the unit as is requires dropping support for older Ubuntu versions.
Feel free to provide an alternative solution not depending on the InvocationID.

**Comment by FR4NK-W** [comment]
@pietdevaere : PR #15 has been merged.

You can test in the [pre-release build](https://packages-test.netsec.inf.ethz.ch/debian/pool/main/s/scion-bootstrapper/) if it also satisfies your use case.

**Comment by FR4NK-W** [comment]
No further feedback since report, PR #15 provides the desired outcome.
